language: rust
before_install:
  - rustup component add rustfmt
script:
  - cargo build --all-features --verbose
  - cargo fmt --all -- --check
  - cargo test --all-features --verbose -- --show-output
